export const COLORS = {
  LABEL: "#42474A",
  HEADER: {
    GRAY_BACKGROUND: "#DADADA",
    LIGHT_GRAY_BACKGROUND: "#F3F3F3",
    BACKGROUND_HOVER: "#A4A4A4",
    PURPLE_BACKGROUND: "#8469CF",
  },
  RADIO: {
    COLOR: "#8E8E93",
    LIGHT_COLOR: "#DADADA",
    CHECKED_COLOR: "#1677FF",
  },
};
