// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Gestao.Data.Contexts;

namespace SME.Pedagogico.Gestao.Data.Migrations
{
    [DbContext(typeof(SMEManagementContext))]
    [Migration("20190517161451_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("StudentId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = "51847417-a0e0-4a5d-918d-4628cdc6f03a",
                            Description = "Desenvolvedor",
                            Value = "0"
                        },
                        new
                        {
                            Id = "8a2775fb-a1bc-4f68-8776-3b5d2afad56c",
                            Description = "COTIC",
                            Value = "1"
                        },
                        new
                        {
                            Id = "bc8d1f53-5888-45b9-9171-ee9bfa671de8",
                            Description = "SME",
                            Value = "2"
                        },
                        new
                        {
                            Id = "3a27ded1-30d0-4131-9a2f-399ca11c4f5c",
                            Description = "COPED",
                            Value = "3"
                        },
                        new
                        {
                            Id = "d97f7c3a-527c-4e49-8355-5bed006d8b88",
                            Description = "DIEFEM",
                            Value = "4"
                        },
                        new
                        {
                            Id = "bb8c9de4-892b-45e2-9599-901770bd1874",
                            Description = "DIEI",
                            Value = "5"
                        },
                        new
                        {
                            Id = "ae65435b-aa1d-44cc-92f1-5f9a32260208",
                            Description = "DIEJA",
                            Value = "6"
                        },
                        new
                        {
                            Id = "c851fa70-ff06-48ea-ac0a-1f1aa7189808",
                            Description = "DIEE",
                            Value = "7"
                        },
                        new
                        {
                            Id = "93f26e54-8568-4634-95b3-0945c1e51ee5",
                            Description = "NTA",
                            Value = "8"
                        },
                        new
                        {
                            Id = "62b5bb0e-080a-42a0-821e-75e757113669",
                            Description = "NTC",
                            Value = "9"
                        },
                        new
                        {
                            Id = "9fe95916-8706-4a28-b0b8-3b324d0365a7",
                            Description = "NTC-NAAPA",
                            Value = "10"
                        },
                        new
                        {
                            Id = "31f676ed-4719-4c73-abc4-ac3f37c5003c",
                            Description = "DIEE-Conveniado",
                            Value = "11"
                        },
                        new
                        {
                            Id = "64c9c2ca-8631-403c-b8a4-21f45c90d6c8",
                            Description = "COPED Básico",
                            Value = "12"
                        },
                        new
                        {
                            Id = "556eb493-223d-4711-ab60-5cf949a7b5cd",
                            Description = "Regional",
                            Value = "13"
                        },
                        new
                        {
                            Id = "d20b19b7-7525-40bb-aae1-f6a2796519f2",
                            Description = "Técnico",
                            Value = "14"
                        },
                        new
                        {
                            Id = "7adae218-5d27-4b2b-9aaa-e9ac6e3eb7f1",
                            Description = "Supervisor DRE",
                            Value = "15"
                        },
                        new
                        {
                            Id = "b3f7ee02-2025-40c8-9d94-8f5d9b0b8ede",
                            Description = "DIPED",
                            Value = "16"
                        },
                        new
                        {
                            Id = "101872c4-6391-4376-938d-5ab3166cb11b",
                            Description = "NAAPA",
                            Value = "17"
                        },
                        new
                        {
                            Id = "10072826-5399-469f-af46-a16b4f35f1a2",
                            Description = "CEFAI",
                            Value = "18"
                        },
                        new
                        {
                            Id = "2cfee8fa-dc82-4b34-96d1-842397ddb9c7",
                            Description = "PAAI",
                            Value = "19"
                        },
                        new
                        {
                            Id = "0e0e5704-bac8-4881-ad2b-d83fea251baa",
                            Description = "DIPED DRE",
                            Value = "20"
                        },
                        new
                        {
                            Id = "46a7aa47-c904-434b-8383-83517476daf7",
                            Description = "Adm DRE",
                            Value = "21"
                        },
                        new
                        {
                            Id = "709bbbd5-d0f7-42d2-9d3e-1a915416834b",
                            Description = "Básico DRE",
                            Value = "22"
                        },
                        new
                        {
                            Id = "ad57030e-a589-4208-8bfa-83627114ac05",
                            Description = "Básico Escola",
                            Value = "23"
                        },
                        new
                        {
                            Id = "83a4de5e-01ef-4a3f-ad57-0992415a2230",
                            Description = "Infantil",
                            Value = "24"
                        },
                        new
                        {
                            Id = "f3bcb5d9-9ffc-4f9c-92c5-8ae3b054817e",
                            Description = "UE Parceira",
                            Value = "25"
                        },
                        new
                        {
                            Id = "6a8b1f22-ab6b-4fa9-8f03-5611a7335d53",
                            Description = "AD",
                            Value = "26"
                        },
                        new
                        {
                            Id = "16195402-0627-4e33-9a7b-2ea1a5a54392",
                            Description = "CP",
                            Value = "27"
                        },
                        new
                        {
                            Id = "11cbed50-1f1c-43b6-82da-e34c04900b8d",
                            Description = "Secretário Escola",
                            Value = "28"
                        },
                        new
                        {
                            Id = "a87433b8-7771-43af-89aa-2b68aebfb853",
                            Description = "COTIC",
                            Value = "29"
                        },
                        new
                        {
                            Id = "7ae09eb2-43a7-4af3-952a-1ea506fe71d3",
                            Description = "UE",
                            Value = "30"
                        },
                        new
                        {
                            Id = "6939cf4d-aea0-4f94-b413-c0666e0be7e8",
                            Description = "CJ E Volante (PEI, ADI)",
                            Value = "31"
                        },
                        new
                        {
                            Id = "0c673b2d-974d-4d2e-b1fa-45c9f0d13551",
                            Description = "Fund. e Inf.",
                            Value = "32"
                        },
                        new
                        {
                            Id = "0bf8f34a-8ad2-4965-8aba-2641d66ba38c",
                            Description = "POA",
                            Value = "33"
                        },
                        new
                        {
                            Id = "f45862f4-4527-4df9-a578-aee5ae8f15a3",
                            Description = "PAP",
                            Value = "34"
                        },
                        new
                        {
                            Id = "c89193a3-0cca-44a4-bc71-b1308f4e3179",
                            Description = "AEE",
                            Value = "35"
                        },
                        new
                        {
                            Id = "ba96524a-f456-4460-8cc3-5271fcd13168",
                            Description = "Readaptado",
                            Value = "33"
                        },
                        new
                        {
                            Id = "dc088cd7-e418-4c96-bf6f-1e5f4ec28291",
                            Description = "ATE",
                            Value = "34"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Session");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoggedUsers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "15a0e83c-6a72-4e90-b065-78f3c4620097",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "2e54c13a-cf62-480e-a148-5cd64a032501",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "2347af68-756c-4bca-9e49-c9a506c9c9cb",
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = "9130abda-0f4a-4adc-a556-81ac17d68dd2",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "6ced5dc6-1d54-4e62-8d6a-1acec0a4051b",
                            Name = "Secretario(a)"
                        },
                        new
                        {
                            Id = "638b7305-8f20-446e-91dd-6b8a826ee1d7",
                            Name = "Auxiliar"
                        },
                        new
                        {
                            Id = "a8856347-f9be-437e-8a57-09358b6f9467",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = "02de0f62-e45a-4c2e-a28b-97eb414db9bb",
                            Name = "Responsavel"
                        },
                        new
                        {
                            Id = "5b2f1c50-f241-4b3a-acf6-f276e37c9b0f",
                            Name = "Aluno"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessLevelId");

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.Code", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("StudentCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithMany("Codes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("TeacherCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithMany("Codes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("LoginStatus")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", "UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", "AccessLevel")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "StudentId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "TeacherId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
