// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Gestao.Data.Contexts;

namespace SME.Pedagogico.Gestao.Data.Migrations
{
    [DbContext(typeof(SMEManagementContext))]
    [Migration("20190606175244_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolCA", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlunoEolCode");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Ordem1Ideia");

                    b.Property<string>("Ordem1Resultado");

                    b.Property<string>("Ordem2Ideia");

                    b.Property<string>("Ordem2Resultado");

                    b.Property<string>("Ordem3Ideia");

                    b.Property<string>("Ordem3Resultado");

                    b.Property<string>("Ordem4Ideia");

                    b.Property<string>("Ordem4Resultado");

                    b.Property<int>("Semestre");

                    b.Property<string>("TurmaEolCode");

                    b.HasKey("Id");

                    b.ToTable("MathPoolCAs");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolCM", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlunoEolCode");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Ordem3Ideia");

                    b.Property<string>("Ordem3Resultado");

                    b.Property<string>("Ordem4Ideia");

                    b.Property<string>("Ordem4Resultado");

                    b.Property<string>("Ordem5Ideia");

                    b.Property<string>("Ordem5Resultado");

                    b.Property<string>("Ordem6Ideia");

                    b.Property<string>("Ordem6Resultado");

                    b.Property<string>("Ordem7Ideia");

                    b.Property<string>("Ordem7Resultado");

                    b.Property<string>("Ordem8Ideia");

                    b.Property<string>("Ordem8Resultado");

                    b.Property<int>("Semestre");

                    b.Property<string>("TurmaEolCode");

                    b.HasKey("Id");

                    b.ToTable("MathPoolCMs");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolNumber", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Algarismos");

                    b.Property<string>("AlunoEolCode");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("Familiares");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Opacos");

                    b.Property<string>("Processo");

                    b.Property<int>("Semestre");

                    b.Property<string>("TerminamZero");

                    b.Property<string>("Transparentes");

                    b.Property<string>("TurmaEolCode");

                    b.Property<string>("ZeroIntercalados");

                    b.HasKey("Id");

                    b.ToTable("MathPoolNumbers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PollType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PollTypeDescription");

                    b.HasKey("Id");

                    b.ToTable("PollType");

                    b.HasData(
                        new
                        {
                            Id = "cc8ac4b6-2e9e-4f06-a719-e94058251ea5",
                            PollTypeDescription = "Sondagem de Português"
                        },
                        new
                        {
                            Id = "9a113be3-7506-49f9-b5df-667ce6ad6bf2",
                            PollTypeDescription = "Sondagem de Matemática"
                        },
                        new
                        {
                            Id = "018b2c19-4f43-4627-8855-b03bf7b95920",
                            PollTypeDescription = "Sondagem de Alfabetização de Matemática"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PortuguesePoll", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("classroomCodeEol");

                    b.Property<string>("dreCodeEol");

                    b.Property<string>("reading1B");

                    b.Property<string>("reading2B");

                    b.Property<string>("reading3B");

                    b.Property<string>("reading4B");

                    b.Property<string>("schoolCodeEol");

                    b.Property<string>("schoolYear");

                    b.Property<string>("studentCodeEol");

                    b.Property<string>("studentNameEol");

                    b.Property<string>("writing1B");

                    b.Property<string>("writing2B");

                    b.Property<string>("writing3B");

                    b.Property<string>("writing4B");

                    b.Property<string>("yearClassroom");

                    b.HasKey("Id");

                    b.ToTable("PortuguesePolls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("StudentId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = "6581796a-8e98-46ad-bb39-40455d3310ff",
                            Description = "Desenvolvedor",
                            Value = "0"
                        },
                        new
                        {
                            Id = "4867a294-3b45-4357-ab69-0f483e46f0f0",
                            Description = "COTIC",
                            Value = "1"
                        },
                        new
                        {
                            Id = "3d1e49de-63b7-498e-b607-9d4ef4ac8a02",
                            Description = "SME",
                            Value = "2"
                        },
                        new
                        {
                            Id = "966c3836-b61b-40e0-8d55-679b147e9a58",
                            Description = "COPED",
                            Value = "3"
                        },
                        new
                        {
                            Id = "09a111c9-bfc6-426d-9559-04e66ca2508e",
                            Description = "DIEFEM",
                            Value = "4"
                        },
                        new
                        {
                            Id = "1b74fe32-4ff8-4bde-af61-796d056b1afd",
                            Description = "DIEI",
                            Value = "5"
                        },
                        new
                        {
                            Id = "ab2b887d-15e5-429d-882b-af40e0870247",
                            Description = "DIEJA",
                            Value = "6"
                        },
                        new
                        {
                            Id = "790eb99e-5371-44fe-8b1b-87b529336705",
                            Description = "DIEE",
                            Value = "7"
                        },
                        new
                        {
                            Id = "792abbf0-2056-4906-beee-a4c2bc6a2304",
                            Description = "NTA",
                            Value = "8"
                        },
                        new
                        {
                            Id = "c4d2972e-a7b5-4be0-b499-e9c2c6bd79ba",
                            Description = "NTC",
                            Value = "9"
                        },
                        new
                        {
                            Id = "b5330752-7ece-4d21-a1b5-fee8accb83a9",
                            Description = "NTC-NAAPA",
                            Value = "10"
                        },
                        new
                        {
                            Id = "17b29d4a-f652-4b9f-aadb-a86d2b8f7b0c",
                            Description = "DIEE-Conveniado",
                            Value = "11"
                        },
                        new
                        {
                            Id = "91cf288a-36f0-48b8-ae08-6d7f26046da4",
                            Description = "COPED Básico",
                            Value = "12"
                        },
                        new
                        {
                            Id = "1d410d23-5a1d-409a-b3dd-082658229070",
                            Description = "Regional",
                            Value = "13"
                        },
                        new
                        {
                            Id = "beaf8491-ea5f-4a76-b5f8-ebb4721bc0db",
                            Description = "Técnico",
                            Value = "14"
                        },
                        new
                        {
                            Id = "405c7282-2589-4b65-889b-71cc559c2f5d",
                            Description = "Supervisor DRE",
                            Value = "15"
                        },
                        new
                        {
                            Id = "25cc4ed0-1344-4270-b878-551d2834c075",
                            Description = "DIPED",
                            Value = "16"
                        },
                        new
                        {
                            Id = "c0adbe15-ae33-4e0d-aff9-c5cc27bfdac5",
                            Description = "NAAPA",
                            Value = "17"
                        },
                        new
                        {
                            Id = "f9ebfe86-5dbf-4da8-9df2-2e25f0a72bea",
                            Description = "CEFAI",
                            Value = "18"
                        },
                        new
                        {
                            Id = "b467b113-cbf8-4acf-a9db-8efc23246363",
                            Description = "PAAI",
                            Value = "19"
                        },
                        new
                        {
                            Id = "3ebd57e4-2600-4171-8071-7e084502d18c",
                            Description = "DIPED DRE",
                            Value = "20"
                        },
                        new
                        {
                            Id = "8e384961-c431-4eac-aef0-dbd24b0c41e3",
                            Description = "Adm DRE",
                            Value = "21"
                        },
                        new
                        {
                            Id = "feb6982b-84b8-4733-82d5-ad059eb474c1",
                            Description = "Básico DRE",
                            Value = "22"
                        },
                        new
                        {
                            Id = "4d88da3f-47aa-4077-a3a6-f17bb3f847b8",
                            Description = "Básico Escola",
                            Value = "23"
                        },
                        new
                        {
                            Id = "a917ecfd-fd8d-43d5-a476-055d99190b13",
                            Description = "Infantil",
                            Value = "24"
                        },
                        new
                        {
                            Id = "75c46e09-9785-4712-a024-e6a94d549581",
                            Description = "UE Parceira",
                            Value = "25"
                        },
                        new
                        {
                            Id = "9db3aaa2-4aab-4d34-a1aa-501c28208a88",
                            Description = "AD",
                            Value = "26"
                        },
                        new
                        {
                            Id = "fc1896b4-d9aa-4c5d-9972-2a4d82311dab",
                            Description = "CP",
                            Value = "27"
                        },
                        new
                        {
                            Id = "98cff31c-cd8c-41f1-bc07-f37240e20174",
                            Description = "Secretário Escola",
                            Value = "28"
                        },
                        new
                        {
                            Id = "3918ef88-1524-402e-ab56-8444c4b398bc",
                            Description = "COTIC",
                            Value = "29"
                        },
                        new
                        {
                            Id = "6907ebef-62cf-4396-b1b8-93a393944860",
                            Description = "UE",
                            Value = "30"
                        },
                        new
                        {
                            Id = "c91bd518-8b0f-4516-af9f-766b471e7024",
                            Description = "CJ E Volante (PEI, ADI)",
                            Value = "31"
                        },
                        new
                        {
                            Id = "2aeb38f5-5324-4015-abe1-f5982efc8563",
                            Description = "Fund. e Inf.",
                            Value = "32"
                        },
                        new
                        {
                            Id = "a2f54490-2284-4e5c-b27d-2f4a22a91ef1",
                            Description = "POA",
                            Value = "33"
                        },
                        new
                        {
                            Id = "2bdfab29-3c14-4f40-9561-71e30ebddb42",
                            Description = "PAP",
                            Value = "34"
                        },
                        new
                        {
                            Id = "144a201e-f3ea-4ab4-ab9f-c265c7014feb",
                            Description = "AEE",
                            Value = "35"
                        },
                        new
                        {
                            Id = "86d480f0-89db-44d8-9a9e-60edf46b5d7b",
                            Description = "Readaptado",
                            Value = "36"
                        },
                        new
                        {
                            Id = "342ff63e-0211-4b06-a935-271b94b1009b",
                            Description = "ATE",
                            Value = "37"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Session");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoggedUsers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.PrivilegedAccess", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("OccupationPlace");

                    b.Property<int>("OccupationPlaceCode");

                    b.HasKey("Id");

                    b.ToTable("PrivilegedAccess");

                    b.HasData(
                        new
                        {
                            Id = "17c9943d-0abb-4a0f-8722-536a8ae52d62",
                            Login = "caique.amcom",
                            Name = "Caique Latorre",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "1125d90a-8b3e-4463-93a2-71d3356611c4",
                            Login = "massato.amcom",
                            Name = "Massato Kanno",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "ccec87a2-dd43-49fb-ad3e-5a2fbc35f360",
                            Login = "Daniel.amcom",
                            Name = "Daniel Matsumoto",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "77175dba-aa8d-4a33-8682-59b8771bf439",
                            Login = "danielli.amcom",
                            Name = "Danielli",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "f6033d9e-0712-4f66-b228-a0b7a27e0083",
                            Login = "jeff.amcom",
                            Name = "Jeff",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "36e510e4-ae6a-4fa2-b668-62891e952245",
                            Login = "aline.amcom",
                            Name = "Aline",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "bbabe6a2-99b7-4ad0-97d8-010ebfd742ac",
                            Login = "gabi.sme",
                            Name = "Gabi",
                            OccupationPlace = "SME",
                            OccupationPlaceCode = 2
                        },
                        new
                        {
                            Id = "5323e4fd-fa90-4323-aa46-87ca04b2cfcc",
                            Login = "heloisa.sme",
                            Name = "Heloisa Giannichi",
                            OccupationPlace = "SME",
                            OccupationPlaceCode = 2
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "683ce3fd-8e56-4dce-b8d9-9d5354dc5e91",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "0507a90a-b70a-4d7a-9379-c9b3b19db0b1",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "f9c81811-05b5-42e0-b89b-6442c5068d2a",
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = "b7a50ae8-fbc7-4430-ae24-d573dc6ce1da",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "0c772e04-4541-4e26-8269-729e2ee65f41",
                            Name = "Secretario(a)"
                        },
                        new
                        {
                            Id = "14b8e37e-51d0-4d0f-843a-c442e71219b7",
                            Name = "Auxiliar"
                        },
                        new
                        {
                            Id = "f3ddbc11-22e2-4459-98fd-7f8bc993839d",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = "49cf6fa3-fcca-4fde-8eb2-d7b89e573bdc",
                            Name = "Responsavel"
                        },
                        new
                        {
                            Id = "1a6f1be2-7ac8-45e2-a0c3-b5d91644a1bc",
                            Name = "Aluno"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessLevelId");

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.Code", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("StudentCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithMany("Codes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("TeacherCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithMany("Codes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("LoginStatus")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", "UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", "AccessLevel")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "StudentId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "TeacherId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
