// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Gestao.Data.Contexts;

namespace SME.Pedagogico.Gestao.Data.Migrations
{
    [DbContext(typeof(SMEManagementContext))]
    [Migration("20190523161853_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PollType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PollTypeDescription");

                    b.HasKey("Id");

                    b.ToTable("PollType");

                    b.HasData(
                        new
                        {
                            Id = "59d55e11-df3b-4b89-86d7-47b83505681e",
                            PollTypeDescription = "Sondagem de Português"
                        },
                        new
                        {
                            Id = "667d4b5f-2f0d-4a95-94c1-57d20bd1d4f5",
                            PollTypeDescription = "Sondagem de Matemática"
                        },
                        new
                        {
                            Id = "6084c793-00b1-4a64-84bd-0e0c35272510",
                            PollTypeDescription = "Sondagem de Alfabetização de Matemática"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PortuguesePoll", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("classroomCodeEol");

                    b.Property<string>("dreCodeEol");

                    b.Property<string>("reading1B");

                    b.Property<string>("reading2B");

                    b.Property<string>("reading3B");

                    b.Property<string>("reading4B");

                    b.Property<string>("schoolCodeEol");

                    b.Property<string>("schoolYear");

                    b.Property<string>("writing1B");

                    b.Property<string>("writing2B");

                    b.Property<string>("writing3B");

                    b.Property<string>("writing4B");

                    b.Property<string>("yearClassroom");

                    b.HasKey("Id");

                    b.ToTable("PortuguesePolls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("StudentId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = "b491f516-e32a-46bf-bfd1-4da213148271",
                            Description = "Desenvolvedor",
                            Value = "0"
                        },
                        new
                        {
                            Id = "8800f115-aa29-4d64-a80a-844bf85b3fe1",
                            Description = "COTIC",
                            Value = "1"
                        },
                        new
                        {
                            Id = "406ef7ea-3117-4e82-935d-885a41323d67",
                            Description = "SME",
                            Value = "2"
                        },
                        new
                        {
                            Id = "9c31717e-ec8c-4140-8061-9775f4a0c123",
                            Description = "COPED",
                            Value = "3"
                        },
                        new
                        {
                            Id = "f4da84a7-6eaf-4238-97c1-0b345303a3a8",
                            Description = "DIEFEM",
                            Value = "4"
                        },
                        new
                        {
                            Id = "5c799345-a574-429d-a8be-cd14d546c73a",
                            Description = "DIEI",
                            Value = "5"
                        },
                        new
                        {
                            Id = "a02a80ed-7def-4c50-b22b-b5eb5d8ab269",
                            Description = "DIEJA",
                            Value = "6"
                        },
                        new
                        {
                            Id = "4068f7b3-39b2-49fa-9423-8d8cb789055f",
                            Description = "DIEE",
                            Value = "7"
                        },
                        new
                        {
                            Id = "3685e30d-9bb6-4ff9-bf78-241204632a81",
                            Description = "NTA",
                            Value = "8"
                        },
                        new
                        {
                            Id = "4285f961-e3b2-4437-9005-6ea7f358e161",
                            Description = "NTC",
                            Value = "9"
                        },
                        new
                        {
                            Id = "eae87bad-f78e-41ba-896c-6fbd57cda7fb",
                            Description = "NTC-NAAPA",
                            Value = "10"
                        },
                        new
                        {
                            Id = "23d66457-09c4-4b67-ad09-b346ea02fc52",
                            Description = "DIEE-Conveniado",
                            Value = "11"
                        },
                        new
                        {
                            Id = "f1f31c54-af9a-4bc1-bf2f-9b62d94aa2b5",
                            Description = "COPED Básico",
                            Value = "12"
                        },
                        new
                        {
                            Id = "24a17593-23a4-4379-87b6-aef4cb38c665",
                            Description = "Regional",
                            Value = "13"
                        },
                        new
                        {
                            Id = "aec55362-8964-4299-9875-9fe2a7a33c42",
                            Description = "Técnico",
                            Value = "14"
                        },
                        new
                        {
                            Id = "9b3c5e58-1d2d-4a19-ac88-0d3517204a08",
                            Description = "Supervisor DRE",
                            Value = "15"
                        },
                        new
                        {
                            Id = "dfa3ff7c-f92f-422a-b6a6-69c412effd81",
                            Description = "DIPED",
                            Value = "16"
                        },
                        new
                        {
                            Id = "a28febe5-f228-4002-8939-ca0727990bd4",
                            Description = "NAAPA",
                            Value = "17"
                        },
                        new
                        {
                            Id = "c11c1ccc-e240-4315-9e3a-ed869f2d8828",
                            Description = "CEFAI",
                            Value = "18"
                        },
                        new
                        {
                            Id = "21303685-449b-4b19-b4f2-002472dc03b4",
                            Description = "PAAI",
                            Value = "19"
                        },
                        new
                        {
                            Id = "b54daba3-9a31-4dfb-ae65-29280042113a",
                            Description = "DIPED DRE",
                            Value = "20"
                        },
                        new
                        {
                            Id = "24556be2-6c56-4a6d-96d3-500519ec8170",
                            Description = "Adm DRE",
                            Value = "21"
                        },
                        new
                        {
                            Id = "225efdd1-3342-4945-a65b-db2613e57561",
                            Description = "Básico DRE",
                            Value = "22"
                        },
                        new
                        {
                            Id = "0f64334c-3d91-4bf1-8d5f-4c8f5022d369",
                            Description = "Básico Escola",
                            Value = "23"
                        },
                        new
                        {
                            Id = "11aa7a3d-ecbe-4539-8378-4def7e225082",
                            Description = "Infantil",
                            Value = "24"
                        },
                        new
                        {
                            Id = "7d527c28-bf04-48d2-a9c2-4c096021789d",
                            Description = "UE Parceira",
                            Value = "25"
                        },
                        new
                        {
                            Id = "fc3dc1aa-dce3-479b-8e3e-80997cebe7a5",
                            Description = "AD",
                            Value = "26"
                        },
                        new
                        {
                            Id = "8a05adb3-a042-4f7d-9d97-edc05aeeabab",
                            Description = "CP",
                            Value = "27"
                        },
                        new
                        {
                            Id = "9141ffc4-95ff-475a-a598-064f6fc0c22a",
                            Description = "Secretário Escola",
                            Value = "28"
                        },
                        new
                        {
                            Id = "52da301a-721a-48cf-bea5-2d708f45505a",
                            Description = "COTIC",
                            Value = "29"
                        },
                        new
                        {
                            Id = "6ee947f5-19ac-4c93-8cac-f33083ebe938",
                            Description = "UE",
                            Value = "30"
                        },
                        new
                        {
                            Id = "bebb8398-7991-4a1f-9c50-a43873a07e0d",
                            Description = "CJ E Volante (PEI, ADI)",
                            Value = "31"
                        },
                        new
                        {
                            Id = "2b61705f-3dd7-4100-8806-96c6137d9c65",
                            Description = "Fund. e Inf.",
                            Value = "32"
                        },
                        new
                        {
                            Id = "fac80129-876c-41fc-a573-b4446c4e4d61",
                            Description = "POA",
                            Value = "33"
                        },
                        new
                        {
                            Id = "79e605e3-d8dc-46a7-bb8f-b71fb3fe53ac",
                            Description = "PAP",
                            Value = "34"
                        },
                        new
                        {
                            Id = "55cf612a-a2b4-4d08-9a67-db76ef6d4732",
                            Description = "AEE",
                            Value = "35"
                        },
                        new
                        {
                            Id = "72823f44-0387-4e0a-b1f4-8cb1c34fe746",
                            Description = "Readaptado",
                            Value = "36"
                        },
                        new
                        {
                            Id = "6ec9d2d9-3a6e-42ab-a62e-7d0b1c8eb432",
                            Description = "ATE",
                            Value = "37"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Session");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoggedUsers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "e23aa1eb-b693-4cb6-8394-0700b1d5b10e",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "225a6048-8c5e-42f0-a6cd-fc8cb18d9797",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "cb58a6ab-a572-4bdb-bcf8-3364f20ae269",
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = "4248fd6c-60f5-4b80-ba68-80b55a7e9446",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "bf3e14cc-20e3-4632-a61b-2cd8f13bb99f",
                            Name = "Secretario(a)"
                        },
                        new
                        {
                            Id = "03eeb0d4-12d3-41be-8f22-78729f22e73c",
                            Name = "Auxiliar"
                        },
                        new
                        {
                            Id = "8eb938db-bd70-45f6-9586-696d30d88ecd",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = "ba4725af-b724-469b-bf5b-1b4edc412aba",
                            Name = "Responsavel"
                        },
                        new
                        {
                            Id = "0f9f7e51-130e-435f-b180-5004f52f6249",
                            Name = "Aluno"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessLevelId");

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.Code", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("StudentCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithMany("Codes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("TeacherCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithMany("Codes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("LoginStatus")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", "UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", "AccessLevel")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "StudentId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "TeacherId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
