// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Gestao.Data.Contexts;

namespace SME.Pedagogico.Gestao.Data.Migrations
{
    [DbContext(typeof(SMEManagementContext))]
    [Migration("20190612214257_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolCA", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlunoEolCode");

                    b.Property<string>("AlunoNome");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Ordem1Ideia");

                    b.Property<string>("Ordem1Resultado");

                    b.Property<string>("Ordem2Ideia");

                    b.Property<string>("Ordem2Resultado");

                    b.Property<string>("Ordem3Ideia");

                    b.Property<string>("Ordem3Resultado");

                    b.Property<string>("Ordem4Ideia");

                    b.Property<string>("Ordem4Resultado");

                    b.Property<int>("Semestre");

                    b.Property<string>("TurmaEolCode");

                    b.HasKey("Id");

                    b.ToTable("MathPoolCAs");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolCM", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlunoEolCode");

                    b.Property<string>("AlunoNome");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Ordem3Ideia");

                    b.Property<string>("Ordem3Resultado");

                    b.Property<string>("Ordem4Ideia");

                    b.Property<string>("Ordem4Resultado");

                    b.Property<string>("Ordem5Ideia");

                    b.Property<string>("Ordem5Resultado");

                    b.Property<string>("Ordem6Ideia");

                    b.Property<string>("Ordem6Resultado");

                    b.Property<string>("Ordem7Ideia");

                    b.Property<string>("Ordem7Resultado");

                    b.Property<string>("Ordem8Ideia");

                    b.Property<string>("Ordem8Resultado");

                    b.Property<int>("Semestre");

                    b.Property<string>("TurmaEolCode");

                    b.HasKey("Id");

                    b.ToTable("MathPoolCMs");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolNumber", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Algarismos");

                    b.Property<string>("AlunoEolCode");

                    b.Property<string>("AlunoNome");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("Familiares");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Opacos");

                    b.Property<string>("Processo");

                    b.Property<int>("Semestre");

                    b.Property<string>("TerminamZero");

                    b.Property<string>("Transparentes");

                    b.Property<string>("TurmaEolCode");

                    b.Property<string>("ZeroIntercalados");

                    b.HasKey("Id");

                    b.ToTable("MathPoolNumbers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PollType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PollTypeDescription");

                    b.HasKey("Id");

                    b.ToTable("PollType");

                    b.HasData(
                        new
                        {
                            Id = "4c274126-5ff8-4a04-b893-777650abe9bf",
                            PollTypeDescription = "Sondagem de Português"
                        },
                        new
                        {
                            Id = "8ebf0fbb-c3e0-4333-b174-f9ce5c3504a3",
                            PollTypeDescription = "Sondagem de Matemática"
                        },
                        new
                        {
                            Id = "9b098a6a-57c2-4893-a2f7-9f735689f84a",
                            PollTypeDescription = "Sondagem de Alfabetização de Matemática"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PortuguesePoll", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("classroomCodeEol");

                    b.Property<string>("dreCodeEol");

                    b.Property<string>("reading1B");

                    b.Property<string>("reading2B");

                    b.Property<string>("reading3B");

                    b.Property<string>("reading4B");

                    b.Property<string>("schoolCodeEol");

                    b.Property<string>("schoolYear");

                    b.Property<string>("studentCodeEol");

                    b.Property<string>("studentNameEol");

                    b.Property<string>("writing1B");

                    b.Property<string>("writing2B");

                    b.Property<string>("writing3B");

                    b.Property<string>("writing4B");

                    b.Property<string>("yearClassroom");

                    b.HasKey("Id");

                    b.ToTable("PortuguesePolls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("StudentId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = "cadf81cf-247f-4d9e-9535-0229b71c0409",
                            Description = "Desenvolvedor",
                            Value = "0"
                        },
                        new
                        {
                            Id = "dd4ff7a2-1c52-408c-aea2-123d8eace7d2",
                            Description = "COTIC",
                            Value = "1"
                        },
                        new
                        {
                            Id = "969bb770-ed9d-4810-871f-47b0e43feb02",
                            Description = "SME",
                            Value = "2"
                        },
                        new
                        {
                            Id = "31ecb7f1-ac69-4b15-be79-38c6522312e1",
                            Description = "COPED",
                            Value = "3"
                        },
                        new
                        {
                            Id = "fc0c9f6f-18a7-4927-a808-3a341844b82c",
                            Description = "DIEFEM",
                            Value = "4"
                        },
                        new
                        {
                            Id = "4bb8555d-9a13-4c97-b018-1d6049c938ea",
                            Description = "DIEI",
                            Value = "5"
                        },
                        new
                        {
                            Id = "64292298-6102-498a-8b88-38170125c7ae",
                            Description = "DIEJA",
                            Value = "6"
                        },
                        new
                        {
                            Id = "ba22c73f-d8b0-4a1d-9979-b3df6d4e9621",
                            Description = "DIEE",
                            Value = "7"
                        },
                        new
                        {
                            Id = "482fa371-c52b-46a5-a4de-518acf913149",
                            Description = "NTA",
                            Value = "8"
                        },
                        new
                        {
                            Id = "d0148ce5-5a97-497c-acaf-8bdb273f9b8e",
                            Description = "NTC",
                            Value = "9"
                        },
                        new
                        {
                            Id = "11bb2496-f8ce-46f6-9376-2183d9547b19",
                            Description = "NTC-NAAPA",
                            Value = "10"
                        },
                        new
                        {
                            Id = "6a955932-0ccb-4fce-9b6d-3cf6dd07f3f9",
                            Description = "DIEE-Conveniado",
                            Value = "11"
                        },
                        new
                        {
                            Id = "7a8ab3d9-7d6b-4956-b3da-ae877382942e",
                            Description = "COPED Básico",
                            Value = "12"
                        },
                        new
                        {
                            Id = "dd0292e3-df74-49fb-bb70-853863fe31fc",
                            Description = "Regional",
                            Value = "13"
                        },
                        new
                        {
                            Id = "cd866005-7452-412e-9a24-3fa3f1dd995b",
                            Description = "Técnico",
                            Value = "14"
                        },
                        new
                        {
                            Id = "900876ad-dcb2-499c-a454-deea9baa423b",
                            Description = "Supervisor DRE",
                            Value = "15"
                        },
                        new
                        {
                            Id = "fcbc2237-4c8d-4254-8c2b-3f2e9866a2ee",
                            Description = "DIPED",
                            Value = "16"
                        },
                        new
                        {
                            Id = "be59e15d-1630-49ee-9188-9f5d7858d75d",
                            Description = "NAAPA",
                            Value = "17"
                        },
                        new
                        {
                            Id = "955ba028-889c-409b-bd18-5715f3d5315a",
                            Description = "CEFAI",
                            Value = "18"
                        },
                        new
                        {
                            Id = "a58dd6dd-10cf-4c37-85ba-ddc2dd14bb72",
                            Description = "PAAI",
                            Value = "19"
                        },
                        new
                        {
                            Id = "61432693-5a1d-4a5b-916a-acf39455e7e5",
                            Description = "DIPED DRE",
                            Value = "20"
                        },
                        new
                        {
                            Id = "24e36273-8863-4504-b35b-aa4951a72a6b",
                            Description = "Adm DRE",
                            Value = "21"
                        },
                        new
                        {
                            Id = "4aa1497d-0a1c-4177-8355-1cdbde685de8",
                            Description = "Básico DRE",
                            Value = "22"
                        },
                        new
                        {
                            Id = "14162a07-47ff-46e3-aeb4-802e1063e6d6",
                            Description = "Básico Escola",
                            Value = "23"
                        },
                        new
                        {
                            Id = "6e63fb73-8d52-4f8f-b3be-ad1735f7e693",
                            Description = "Infantil",
                            Value = "24"
                        },
                        new
                        {
                            Id = "5202bfe8-f0bf-4634-83b7-b4bc510ffedf",
                            Description = "UE Parceira",
                            Value = "25"
                        },
                        new
                        {
                            Id = "2edc2133-0d17-4951-90b1-5b51d4e0599d",
                            Description = "AD",
                            Value = "26"
                        },
                        new
                        {
                            Id = "6621d049-b4fd-46fb-b174-371727bd5446",
                            Description = "CP",
                            Value = "27"
                        },
                        new
                        {
                            Id = "261ee896-f46c-417d-b467-5f7e1aa8ff58",
                            Description = "Secretário Escola",
                            Value = "28"
                        },
                        new
                        {
                            Id = "72519030-49bf-403d-b357-f9457d694cc8",
                            Description = "COTIC",
                            Value = "29"
                        },
                        new
                        {
                            Id = "98cfbfb6-0ce3-4699-ac60-016a88f9e793",
                            Description = "UE",
                            Value = "30"
                        },
                        new
                        {
                            Id = "ae452529-2f1c-4cc5-b9f0-36558a52e5f3",
                            Description = "CJ E Volante (PEI, ADI)",
                            Value = "31"
                        },
                        new
                        {
                            Id = "49f8c684-592b-49af-b095-eae7e617d22d",
                            Description = "Fund. e Inf.",
                            Value = "32"
                        },
                        new
                        {
                            Id = "36b42579-c7b6-405a-954b-d218e8f19f89",
                            Description = "POA",
                            Value = "33"
                        },
                        new
                        {
                            Id = "cb4d8612-8e66-4169-b126-5b2b23acd7c3",
                            Description = "PAP",
                            Value = "34"
                        },
                        new
                        {
                            Id = "46127b64-698d-40cb-8ea2-c2ddd31a6934",
                            Description = "AEE",
                            Value = "35"
                        },
                        new
                        {
                            Id = "cbdbdc1c-edf3-41f7-b995-29d6007080f8",
                            Description = "Readaptado",
                            Value = "36"
                        },
                        new
                        {
                            Id = "298b6004-bbb2-4ba8-af9a-270c4d006eae",
                            Description = "ATE",
                            Value = "37"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Session");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoggedUsers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.PrivilegedAccess", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DreCodeEol");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("OccupationPlace");

                    b.Property<int>("OccupationPlaceCode");

                    b.HasKey("Id");

                    b.ToTable("PrivilegedAccess");

                    b.HasData(
                        new
                        {
                            Id = "af58bd68-9c16-4f7d-93b3-f5d43b68e02f",
                            DreCodeEol = "",
                            Login = "caique.amcom",
                            Name = "Caique Latorre",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "a6ff4837-beef-4962-b41a-7c3930be66c1",
                            DreCodeEol = "",
                            Login = "massato.amcom",
                            Name = "Massato Kanno",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "eae86c1c-35ae-48bc-9339-9eb62829b738",
                            DreCodeEol = "",
                            Login = "daniel.amcom",
                            Name = "Daniel Matsumoto",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "ace79f34-53ad-431c-ae8e-3465f75b9ae0",
                            DreCodeEol = "",
                            Login = "danielli.amcom",
                            Name = "Danielli",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "216ec9c7-514c-4148-94c9-03d15537e676",
                            DreCodeEol = "",
                            Login = "jeff.amcom",
                            Name = "Jeff",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "8a09c6b0-275f-4a86-a8be-751067cc7b71",
                            DreCodeEol = "",
                            Login = "aline.amcom",
                            Name = "Aline",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "16c0c94b-05f0-48ad-99c8-f06250fe464b",
                            DreCodeEol = "",
                            Login = "gabi.sme",
                            Name = "Gabi",
                            OccupationPlace = "SME",
                            OccupationPlaceCode = 2
                        },
                        new
                        {
                            Id = "09e0d3a7-58f2-4648-a492-bf8cd27de096",
                            DreCodeEol = "",
                            Login = "heloisa.sme",
                            Name = "Heloisa Giannichi",
                            OccupationPlace = "SME",
                            OccupationPlaceCode = 2
                        },
                        new
                        {
                            Id = "befd7a2a-5f02-4107-b506-d110ac1c788c",
                            DreCodeEol = "108100",
                            Login = "7418078",
                            Name = "Annaa Luisa de Castro",
                            OccupationPlace = "DIRETORIA REGIONAL DE EDUCACAO BUTANTA",
                            OccupationPlaceCode = 3
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "9c9305ae-e8ab-4848-8fcc-ea4761261dd3",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "ddc01c24-25b2-4564-8d56-79d830e29eac",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "ac399962-688c-41c8-b20f-e396492bcf67",
                            Name = "CP"
                        },
                        new
                        {
                            Id = "b6c67d93-82aa-4516-aa25-9eadcafe5ce5",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "5801862d-91b9-4d95-86ff-909c18545aef",
                            Name = "Secretario(a)"
                        },
                        new
                        {
                            Id = "516f38fd-7eea-4f1e-bea8-ee4ceed971e3",
                            Name = "Auxiliar"
                        },
                        new
                        {
                            Id = "dd19ab68-f596-4de0-912f-b7a9312b752e",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = "ca142c98-69eb-4dfe-8253-1af96b6d4acb",
                            Name = "Responsavel"
                        },
                        new
                        {
                            Id = "755eaf63-ac5d-404c-90b3-6067737e20f8",
                            Name = "Aluno"
                        },
                        new
                        {
                            Id = "1ef3debd-761e-485a-b93b-194dae0fa3e8",
                            Name = "Adm DRE"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessLevelId");

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.Code", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("StudentCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithMany("Codes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("TeacherCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithMany("Codes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("LoginStatus")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", "UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", "AccessLevel")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "StudentId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "TeacherId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
