// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Gestao.Data.Contexts;

namespace SME.Pedagogico.Gestao.Data.Migrations
{
    [DbContext(typeof(SMEManagementContext))]
    [Migration("20190528021628_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PollType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PollTypeDescription");

                    b.HasKey("Id");

                    b.ToTable("PollType");

                    b.HasData(
                        new
                        {
                            Id = "9d55c349-8153-4a12-ae78-3eb3b80cf288",
                            PollTypeDescription = "Sondagem de Português"
                        },
                        new
                        {
                            Id = "5ded59ca-bd0e-46ba-9a91-c17b89d86736",
                            PollTypeDescription = "Sondagem de Matemática"
                        },
                        new
                        {
                            Id = "9863c6d1-d203-4edc-b5e4-7680f5ed9ada",
                            PollTypeDescription = "Sondagem de Alfabetização de Matemática"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PortuguesePoll", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("classroomCodeEol");

                    b.Property<string>("dreCodeEol");

                    b.Property<string>("reading1B");

                    b.Property<string>("reading2B");

                    b.Property<string>("reading3B");

                    b.Property<string>("reading4B");

                    b.Property<string>("schoolCodeEol");

                    b.Property<string>("schoolYear");

                    b.Property<string>("studentCodeEol");

                    b.Property<string>("writing1B");

                    b.Property<string>("writing2B");

                    b.Property<string>("writing3B");

                    b.Property<string>("writing4B");

                    b.Property<string>("yearClassroom");

                    b.HasKey("Id");

                    b.ToTable("PortuguesePolls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("StudentId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = "6e57bd06-df9d-4086-900a-b4ba3d97af8a",
                            Description = "Desenvolvedor",
                            Value = "0"
                        },
                        new
                        {
                            Id = "105988b7-f897-4980-8bd0-0a6203f6c97f",
                            Description = "COTIC",
                            Value = "1"
                        },
                        new
                        {
                            Id = "baeb4587-f4b2-4650-a1c8-c968f8abf7dc",
                            Description = "SME",
                            Value = "2"
                        },
                        new
                        {
                            Id = "81fff531-f5e0-4474-b193-31d82a20be40",
                            Description = "COPED",
                            Value = "3"
                        },
                        new
                        {
                            Id = "752b2174-ab94-46bd-9257-004d335b0993",
                            Description = "DIEFEM",
                            Value = "4"
                        },
                        new
                        {
                            Id = "5c4b286f-3ca4-47aa-a30b-4c6f20d80ffa",
                            Description = "DIEI",
                            Value = "5"
                        },
                        new
                        {
                            Id = "6da5534f-c7ff-4da9-bcc4-3437900936e6",
                            Description = "DIEJA",
                            Value = "6"
                        },
                        new
                        {
                            Id = "bdf94c64-f8b4-4da4-87e9-3213e5e9f30c",
                            Description = "DIEE",
                            Value = "7"
                        },
                        new
                        {
                            Id = "665cce38-0a70-4950-b243-9fe4919385de",
                            Description = "NTA",
                            Value = "8"
                        },
                        new
                        {
                            Id = "df3297dc-a677-4b1b-9bb0-6817dc69b7c1",
                            Description = "NTC",
                            Value = "9"
                        },
                        new
                        {
                            Id = "a30a11ec-73d3-455f-a686-91e07131db14",
                            Description = "NTC-NAAPA",
                            Value = "10"
                        },
                        new
                        {
                            Id = "88fe6e3c-2bd9-490c-9d88-f2c00f3b9b89",
                            Description = "DIEE-Conveniado",
                            Value = "11"
                        },
                        new
                        {
                            Id = "4810a4f4-9b6a-4e41-8bd9-8d4c66da7bbe",
                            Description = "COPED Básico",
                            Value = "12"
                        },
                        new
                        {
                            Id = "5a5275df-b702-422e-8009-16d890690548",
                            Description = "Regional",
                            Value = "13"
                        },
                        new
                        {
                            Id = "f57b5396-9b7c-4a7b-bfdc-520c6f680a4d",
                            Description = "Técnico",
                            Value = "14"
                        },
                        new
                        {
                            Id = "ba0adabe-1e56-4899-9826-fa40f95ab117",
                            Description = "Supervisor DRE",
                            Value = "15"
                        },
                        new
                        {
                            Id = "e0f3ea9d-14fe-4c96-a9ad-449fd1e4e2e1",
                            Description = "DIPED",
                            Value = "16"
                        },
                        new
                        {
                            Id = "f9912e39-6c63-46f2-8239-a771edd9a9ea",
                            Description = "NAAPA",
                            Value = "17"
                        },
                        new
                        {
                            Id = "9b631a08-ee65-4b39-84e5-4c2ea436eef8",
                            Description = "CEFAI",
                            Value = "18"
                        },
                        new
                        {
                            Id = "f98e0f55-072d-48ab-98bb-2fe37603f660",
                            Description = "PAAI",
                            Value = "19"
                        },
                        new
                        {
                            Id = "0e2aaf43-8f41-48ab-bdef-b749cf2d0cc8",
                            Description = "DIPED DRE",
                            Value = "20"
                        },
                        new
                        {
                            Id = "be548576-329a-48b4-aefd-25242706ee9d",
                            Description = "Adm DRE",
                            Value = "21"
                        },
                        new
                        {
                            Id = "191c2c1a-d19d-4332-9eb3-592978a1c252",
                            Description = "Básico DRE",
                            Value = "22"
                        },
                        new
                        {
                            Id = "003d355f-95f8-45f9-80e0-4baa0fb13f2a",
                            Description = "Básico Escola",
                            Value = "23"
                        },
                        new
                        {
                            Id = "6cca3723-99ad-40f9-b354-a67a44ee8672",
                            Description = "Infantil",
                            Value = "24"
                        },
                        new
                        {
                            Id = "40b3d294-d342-4a00-a3d1-47e6ad5eef10",
                            Description = "UE Parceira",
                            Value = "25"
                        },
                        new
                        {
                            Id = "8600e523-4abc-46f4-8bb2-c6a38d3799de",
                            Description = "AD",
                            Value = "26"
                        },
                        new
                        {
                            Id = "75891ab4-b76a-45c9-9d1a-8324550c3e06",
                            Description = "CP",
                            Value = "27"
                        },
                        new
                        {
                            Id = "51afbfd1-d355-423a-9b20-607a5f0f6020",
                            Description = "Secretário Escola",
                            Value = "28"
                        },
                        new
                        {
                            Id = "f0ea4dd4-5a60-44d5-a622-ed106a9d6d04",
                            Description = "COTIC",
                            Value = "29"
                        },
                        new
                        {
                            Id = "ab281bac-1e57-4f9b-b657-5e8abb9e9915",
                            Description = "UE",
                            Value = "30"
                        },
                        new
                        {
                            Id = "bda0b10e-6550-4637-96b0-3db53078deb9",
                            Description = "CJ E Volante (PEI, ADI)",
                            Value = "31"
                        },
                        new
                        {
                            Id = "1be173c6-f5eb-4247-b03c-8b924a9f48c8",
                            Description = "Fund. e Inf.",
                            Value = "32"
                        },
                        new
                        {
                            Id = "8b77c60d-7be4-464e-9a1b-2a2379d741c4",
                            Description = "POA",
                            Value = "33"
                        },
                        new
                        {
                            Id = "3b788a18-c920-48e1-b114-8572f703d219",
                            Description = "PAP",
                            Value = "34"
                        },
                        new
                        {
                            Id = "51610fc5-25a5-438e-b4e0-74f56dfdb72f",
                            Description = "AEE",
                            Value = "35"
                        },
                        new
                        {
                            Id = "3ff47b49-e800-4aa7-a3e6-5069699eedc5",
                            Description = "Readaptado",
                            Value = "36"
                        },
                        new
                        {
                            Id = "76575987-8ad8-473a-b038-5b930134567e",
                            Description = "ATE",
                            Value = "37"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Session");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoggedUsers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "e38c72f7-c981-4a04-822d-150953a82f80",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "cff47dc2-be18-4126-a8e4-a80a43585a08",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "09ff8eb8-69ce-4803-bb2d-aa89e2ca63cb",
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = "12bea91b-0d06-481e-a66c-a9d4dc8dd094",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "2209799e-e4a7-43ad-bd10-ff47164552f7",
                            Name = "Secretario(a)"
                        },
                        new
                        {
                            Id = "b402aa41-b41c-4d9c-821b-62a62aaffdef",
                            Name = "Auxiliar"
                        },
                        new
                        {
                            Id = "e3c0ed73-5b8b-49ab-81a7-6a82d9cc3528",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = "351d07e9-3ad8-4147-98c3-dfb640d7fa42",
                            Name = "Responsavel"
                        },
                        new
                        {
                            Id = "d0404d69-3d75-45d7-8f98-4d64003fcb66",
                            Name = "Aluno"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessLevelId");

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.Code", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("StudentCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithMany("Codes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("TeacherCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithMany("Codes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("LoginStatus")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", "UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", "AccessLevel")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "StudentId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "TeacherId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
