// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Gestao.Data.Contexts;

namespace SME.Pedagogico.Gestao.Data.Migrations
{
    [DbContext(typeof(SMEManagementContext))]
    partial class SMEManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolCA", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlunoEolCode");

                    b.Property<string>("AlunoNome");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Ordem1Ideia");

                    b.Property<string>("Ordem1Resultado");

                    b.Property<string>("Ordem2Ideia");

                    b.Property<string>("Ordem2Resultado");

                    b.Property<string>("Ordem3Ideia");

                    b.Property<string>("Ordem3Resultado");

                    b.Property<string>("Ordem4Ideia");

                    b.Property<string>("Ordem4Resultado");

                    b.Property<int>("Semestre");

                    b.Property<string>("TurmaEolCode");

                    b.HasKey("Id");

                    b.ToTable("MathPoolCAs");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolCM", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlunoEolCode");

                    b.Property<string>("AlunoNome");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Ordem3Ideia");

                    b.Property<string>("Ordem3Resultado");

                    b.Property<string>("Ordem4Ideia");

                    b.Property<string>("Ordem4Resultado");

                    b.Property<string>("Ordem5Ideia");

                    b.Property<string>("Ordem5Resultado");

                    b.Property<string>("Ordem6Ideia");

                    b.Property<string>("Ordem6Resultado");

                    b.Property<string>("Ordem7Ideia");

                    b.Property<string>("Ordem7Resultado");

                    b.Property<string>("Ordem8Ideia");

                    b.Property<string>("Ordem8Resultado");

                    b.Property<int>("Semestre");

                    b.Property<string>("TurmaEolCode");

                    b.HasKey("Id");

                    b.ToTable("MathPoolCMs");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.MathPoolNumber", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Algarismos");

                    b.Property<string>("AlunoEolCode");

                    b.Property<string>("AlunoNome");

                    b.Property<int>("AnoLetivo");

                    b.Property<int>("AnoTurma");

                    b.Property<string>("DreEolCode");

                    b.Property<string>("EscolaEolCode");

                    b.Property<string>("Familiares");

                    b.Property<string>("NumeroChamada");

                    b.Property<string>("Opacos");

                    b.Property<string>("Processo");

                    b.Property<int>("Semestre");

                    b.Property<string>("TerminamZero");

                    b.Property<string>("Transparentes");

                    b.Property<string>("TurmaEolCode");

                    b.Property<string>("ZeroIntercalados");

                    b.HasKey("Id");

                    b.ToTable("MathPoolNumbers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PollType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PollTypeDescription");

                    b.HasKey("Id");

                    b.ToTable("PollType");

                    b.HasData(
                        new
                        {
                            Id = "f1430a58-b3d4-4c5c-877e-2a018c140802",
                            PollTypeDescription = "Sondagem de Português"
                        },
                        new
                        {
                            Id = "88532a82-0e95-4f49-a72c-b254149aa392",
                            PollTypeDescription = "Sondagem de Matemática"
                        },
                        new
                        {
                            Id = "9414d64b-c1ff-42dc-b11e-230199646c85",
                            PollTypeDescription = "Sondagem de Alfabetização de Matemática"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.PortuguesePoll", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("classroomCodeEol");

                    b.Property<string>("dreCodeEol");

                    b.Property<string>("reading1B");

                    b.Property<string>("reading2B");

                    b.Property<string>("reading3B");

                    b.Property<string>("reading4B");

                    b.Property<string>("schoolCodeEol");

                    b.Property<string>("schoolYear");

                    b.Property<string>("studentCodeEol");

                    b.Property<string>("studentNameEol");

                    b.Property<string>("writing1B");

                    b.Property<string>("writing2B");

                    b.Property<string>("writing3B");

                    b.Property<string>("writing4B");

                    b.Property<string>("yearClassroom");

                    b.HasKey("Id");

                    b.ToTable("PortuguesePolls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("StudentId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = "adbbbec0-0c35-4f85-bde4-1a9918bfb7ca",
                            Description = "Desenvolvedor",
                            Value = "0"
                        },
                        new
                        {
                            Id = "2fc32220-cfda-4566-9a3c-1d265e0ce638",
                            Description = "COTIC",
                            Value = "1"
                        },
                        new
                        {
                            Id = "db48b712-d8fd-4f0f-983e-dbebab9f3bf6",
                            Description = "SME",
                            Value = "2"
                        },
                        new
                        {
                            Id = "3125fd44-e22c-4738-9727-7dbf2b15e155",
                            Description = "COPED",
                            Value = "3"
                        },
                        new
                        {
                            Id = "57544683-bbdc-41ea-a191-ded07e277afa",
                            Description = "DIEFEM",
                            Value = "4"
                        },
                        new
                        {
                            Id = "ae1749fe-0d02-4463-8e21-b0bab1d6c4de",
                            Description = "DIEI",
                            Value = "5"
                        },
                        new
                        {
                            Id = "af19d00a-7ad3-45eb-8cfb-76ef30bde5ec",
                            Description = "DIEJA",
                            Value = "6"
                        },
                        new
                        {
                            Id = "b5c0cf7c-9d77-4278-8a9c-1ee9b96036c6",
                            Description = "DIEE",
                            Value = "7"
                        },
                        new
                        {
                            Id = "d1843d78-cd31-40c4-93e3-f697d6527889",
                            Description = "NTA",
                            Value = "8"
                        },
                        new
                        {
                            Id = "c7b49ce1-baaa-44e9-84d6-18581691b930",
                            Description = "NTC",
                            Value = "9"
                        },
                        new
                        {
                            Id = "687e5f86-2534-4800-ab2f-dc9d8acde50c",
                            Description = "NTC-NAAPA",
                            Value = "10"
                        },
                        new
                        {
                            Id = "fc176876-78b4-4ccc-adfe-4c8b78f33bb6",
                            Description = "DIEE-Conveniado",
                            Value = "11"
                        },
                        new
                        {
                            Id = "944f49cd-4464-40de-918b-e4bc548f66e6",
                            Description = "COPED Básico",
                            Value = "12"
                        },
                        new
                        {
                            Id = "757c5070-221e-414e-8709-c73e119e7036",
                            Description = "Regional",
                            Value = "13"
                        },
                        new
                        {
                            Id = "0a2646c1-6843-471f-ace1-b59bf07d7fb1",
                            Description = "Técnico",
                            Value = "14"
                        },
                        new
                        {
                            Id = "e89de49e-2613-46f3-a009-ecd2e6131029",
                            Description = "Supervisor DRE",
                            Value = "15"
                        },
                        new
                        {
                            Id = "ee81f763-667f-4afb-b249-c455968ebba3",
                            Description = "DIPED",
                            Value = "16"
                        },
                        new
                        {
                            Id = "dc5bcecd-bd36-4f32-b325-a0ba8084e626",
                            Description = "NAAPA",
                            Value = "17"
                        },
                        new
                        {
                            Id = "f35c3438-0b50-4d33-aa1e-728f1ce1fcba",
                            Description = "CEFAI",
                            Value = "18"
                        },
                        new
                        {
                            Id = "7560974e-037c-4042-91e3-4fc5d8dc3cdc",
                            Description = "PAAI",
                            Value = "19"
                        },
                        new
                        {
                            Id = "fc4c8c41-970a-407c-a64e-d3f203d1a6d2",
                            Description = "DIPED DRE",
                            Value = "20"
                        },
                        new
                        {
                            Id = "3ae21047-eb90-4007-ba34-39bcfc719356",
                            Description = "Adm DRE",
                            Value = "21"
                        },
                        new
                        {
                            Id = "4b55dc84-e236-457e-b9a8-260b31c72567",
                            Description = "Básico DRE",
                            Value = "22"
                        },
                        new
                        {
                            Id = "6d78b480-07a7-40f5-92d8-af6d869c82ff",
                            Description = "Básico Escola",
                            Value = "23"
                        },
                        new
                        {
                            Id = "92685597-9824-4c7f-8640-1bd83b5b5f4a",
                            Description = "Infantil",
                            Value = "24"
                        },
                        new
                        {
                            Id = "c547a2d7-ac77-4eed-851d-811075dd070d",
                            Description = "UE Parceira",
                            Value = "25"
                        },
                        new
                        {
                            Id = "a9df3c08-7a31-4679-87e1-a5ef605b99e6",
                            Description = "AD",
                            Value = "26"
                        },
                        new
                        {
                            Id = "88d95083-d038-4660-8304-eea956c04018",
                            Description = "CP",
                            Value = "27"
                        },
                        new
                        {
                            Id = "0945f6af-dacd-46b8-bcf5-9b077e0109d8",
                            Description = "Secretário Escola",
                            Value = "28"
                        },
                        new
                        {
                            Id = "4e6228cc-e90f-4194-bda1-3e9746689342",
                            Description = "COTIC",
                            Value = "29"
                        },
                        new
                        {
                            Id = "98905c88-ab72-4424-ab37-8904d073d6d2",
                            Description = "UE",
                            Value = "30"
                        },
                        new
                        {
                            Id = "4a1b57a3-1fcd-44d8-939f-b5b9b69b4214",
                            Description = "CJ E Volante (PEI, ADI)",
                            Value = "31"
                        },
                        new
                        {
                            Id = "6a8c4739-4aee-4e20-826f-754fa0ae04d0",
                            Description = "Fund. e Inf.",
                            Value = "32"
                        },
                        new
                        {
                            Id = "12363c07-b4e9-4e70-8f8e-c1a457435875",
                            Description = "POA",
                            Value = "33"
                        },
                        new
                        {
                            Id = "6d74108e-a9f1-42ed-89c9-8588fd0278a3",
                            Description = "PAP",
                            Value = "34"
                        },
                        new
                        {
                            Id = "8abffbf3-2331-43ca-8d1e-88a618abd015",
                            Description = "AEE",
                            Value = "35"
                        },
                        new
                        {
                            Id = "c3fc2a68-8c26-425b-96a9-21faaa851710",
                            Description = "Readaptado",
                            Value = "36"
                        },
                        new
                        {
                            Id = "a9edbdc9-c767-40dc-a339-c19268a4b7af",
                            Description = "ATE",
                            Value = "37"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Session");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoggedUsers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.PrivilegedAccess", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("OccupationPlace");

                    b.Property<int>("OccupationPlaceCode");

                    b.HasKey("Id");

                    b.ToTable("PrivilegedAccess");

                    b.HasData(
                        new
                        {
                            Id = "14387cbc-39bf-433b-aa75-10be5ad62be5",
                            Login = "caique.amcom",
                            Name = "Caique Latorre",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "32846a51-c702-4b44-933b-041cf1c72a2e",
                            Login = "massato.amcom",
                            Name = "Massato Kanno",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "5db8fe18-34f0-47d0-81e4-67031d8148ad",
                            Login = "daniel.amcom",
                            Name = "Daniel Matsumoto",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "5f23102d-0d93-41c3-9996-e91553f79587",
                            Login = "danielli.amcom",
                            Name = "Danielli",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "5ec54af9-43b6-482a-b009-b89ec1ff0664",
                            Login = "jeff.amcom",
                            Name = "Jeff",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "8933008c-39ba-4d4f-964f-1bac19bab760",
                            Login = "aline.amcom",
                            Name = "Aline",
                            OccupationPlace = "AMCOM",
                            OccupationPlaceCode = 1
                        },
                        new
                        {
                            Id = "c90d2dc9-9bbc-437a-8589-2f6d904e765c",
                            Login = "gabi.sme",
                            Name = "Gabi",
                            OccupationPlace = "SME",
                            OccupationPlaceCode = 2
                        },
                        new
                        {
                            Id = "afd6e78f-a79d-4d1f-a4c1-52071b3336be",
                            Login = "heloisa.sme",
                            Name = "Heloisa Giannichi",
                            OccupationPlace = "SME",
                            OccupationPlaceCode = 2
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "c3d3c868-61b4-43f3-9a3a-f9034e8418bb",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "9b40b6fe-c0cb-4fc4-b623-fa2b19b3be67",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "d9681626-cd3e-4950-9429-e433a5d650ea",
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = "1c9d2cfa-bb95-4fea-9fa1-2493ebe82557",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "d89bffe2-a311-4dd0-95ca-382a3de5dce4",
                            Name = "Secretario(a)"
                        },
                        new
                        {
                            Id = "1ab4ef55-69c4-4ce0-94cf-1e4a0eae28c2",
                            Name = "Auxiliar"
                        },
                        new
                        {
                            Id = "fca19160-5802-4be1-ac3f-556e3669dd91",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = "3e85e35d-ddb0-413a-b062-1a1fc9155536",
                            Name = "Responsavel"
                        },
                        new
                        {
                            Id = "429da32d-c950-415e-9aba-de706325cca0",
                            Name = "Aluno"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessLevelId");

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.Code", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("StudentCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithMany("Codes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("TeacherCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithMany("Codes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("LoginStatus")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", "UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", "AccessLevel")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "StudentId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "TeacherId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
