// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Pedagogico.Gestao.Data.Contexts;

namespace SME.Pedagogico.Gestao.Data.Migrations
{
    [DbContext(typeof(SMEManagementContext))]
    partial class SMEManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("StudentId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCodes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = "ef76b295-c3ee-488e-99c7-48931c641e16",
                            Description = "Desenvolvedor",
                            Value = "0"
                        },
                        new
                        {
                            Id = "77d791c5-f86d-45d7-af0a-cb996c77f692",
                            Description = "COTIC",
                            Value = "1"
                        },
                        new
                        {
                            Id = "925bcb7e-7fd6-4cdf-9b2f-9f23deb837ea",
                            Description = "SME",
                            Value = "2"
                        },
                        new
                        {
                            Id = "5c520ef1-5f6f-43c7-b61f-4a361fa8b33f",
                            Description = "COPED",
                            Value = "3"
                        },
                        new
                        {
                            Id = "c664dfaa-3f7a-4ebe-bf4d-9c40840ac4d0",
                            Description = "DIEFEM",
                            Value = "4"
                        },
                        new
                        {
                            Id = "6f8597bc-df26-401c-a411-5d368a600ed0",
                            Description = "DIEI",
                            Value = "5"
                        },
                        new
                        {
                            Id = "f6b67754-88f5-4908-b62f-66234b314b34",
                            Description = "DIEJA",
                            Value = "6"
                        },
                        new
                        {
                            Id = "ad6366f8-0eea-4ed7-83ba-8c69a27bdc2c",
                            Description = "DIEE",
                            Value = "7"
                        },
                        new
                        {
                            Id = "d47ac0d5-9202-47fc-985f-773b765723d1",
                            Description = "NTA",
                            Value = "8"
                        },
                        new
                        {
                            Id = "2ef96d4c-56ff-48d3-a685-de99c88d1eb0",
                            Description = "NTC",
                            Value = "9"
                        },
                        new
                        {
                            Id = "5d3d83b4-91d0-4cce-8434-dff59ee57afc",
                            Description = "NTC-NAAPA",
                            Value = "10"
                        },
                        new
                        {
                            Id = "8c040b83-3420-4e91-ba69-31746a870279",
                            Description = "DIEE-Conveniado",
                            Value = "11"
                        },
                        new
                        {
                            Id = "9f3848a7-8edc-4dbe-9333-8e1781b95b8f",
                            Description = "COPED Básico",
                            Value = "12"
                        },
                        new
                        {
                            Id = "0e920ec1-6701-4ac2-9258-f486eda17623",
                            Description = "Regional",
                            Value = "13"
                        },
                        new
                        {
                            Id = "6234ab73-522f-42b5-8833-1ef07286b0be",
                            Description = "Técnico",
                            Value = "14"
                        },
                        new
                        {
                            Id = "0b82c94c-29ba-4300-aeed-b2fb9f311de4",
                            Description = "Supervisor DRE",
                            Value = "15"
                        },
                        new
                        {
                            Id = "41783fe9-7ab3-4f4f-8d59-a10966e73b6a",
                            Description = "DIPED",
                            Value = "16"
                        },
                        new
                        {
                            Id = "0a89e0bd-cd67-4c34-b45b-5cefc6e58971",
                            Description = "NAAPA",
                            Value = "17"
                        },
                        new
                        {
                            Id = "ab00fb83-6ad1-47b7-ac54-cb1afea9f558",
                            Description = "CEFAI",
                            Value = "18"
                        },
                        new
                        {
                            Id = "870cfba9-a19c-4afb-9f95-f7ac4742d07a",
                            Description = "PAAI",
                            Value = "19"
                        },
                        new
                        {
                            Id = "5b2e4668-12d9-4344-86f0-9badba1d9fb0",
                            Description = "DIPED DRE",
                            Value = "20"
                        },
                        new
                        {
                            Id = "6a8027a8-b5cc-4db5-b9ca-4166a0fb0862",
                            Description = "Adm DRE",
                            Value = "21"
                        },
                        new
                        {
                            Id = "c20ae596-858d-4187-a0a1-6cfec18f499f",
                            Description = "Básico DRE",
                            Value = "22"
                        },
                        new
                        {
                            Id = "4ad2aecd-01c1-4aa8-ab59-c6ef9f0add74",
                            Description = "Básico Escola",
                            Value = "23"
                        },
                        new
                        {
                            Id = "57393d2f-64ba-49b7-8b7c-8e48d8841d5a",
                            Description = "Infantil",
                            Value = "24"
                        },
                        new
                        {
                            Id = "151ecf2d-05c1-4c53-b044-6cd8032209e6",
                            Description = "UE Parceira",
                            Value = "25"
                        },
                        new
                        {
                            Id = "4e81202d-03e9-49dc-b32e-409271fa7cf5",
                            Description = "AD",
                            Value = "26"
                        },
                        new
                        {
                            Id = "1620a652-48a7-46c4-81ee-0b02f4696f9e",
                            Description = "CP",
                            Value = "27"
                        },
                        new
                        {
                            Id = "56c72f2e-c17d-470f-a355-47f24e017872",
                            Description = "Secretário Escola",
                            Value = "28"
                        },
                        new
                        {
                            Id = "48650492-1ff3-401c-a69c-bac10adb227c",
                            Description = "COTIC",
                            Value = "29"
                        },
                        new
                        {
                            Id = "de749335-8120-432f-82df-04f83783fa3b",
                            Description = "UE",
                            Value = "30"
                        },
                        new
                        {
                            Id = "80ba85c3-2d51-4bf3-9de2-290f140f7103",
                            Description = "CJ E Volante (PEI, ADI)",
                            Value = "31"
                        },
                        new
                        {
                            Id = "42ccf8f6-47c9-4a8e-98c3-4767cb00967a",
                            Description = "Fund. e Inf.",
                            Value = "32"
                        },
                        new
                        {
                            Id = "767c06f0-9847-4358-bd10-bd4b2b1ad118",
                            Description = "POA",
                            Value = "33"
                        },
                        new
                        {
                            Id = "bc56eb95-437c-478c-b748-e159cc9db646",
                            Description = "PAP",
                            Value = "34"
                        },
                        new
                        {
                            Id = "3376f838-e4e8-4bdc-a371-7ba50e5f2bf3",
                            Description = "AEE",
                            Value = "35"
                        },
                        new
                        {
                            Id = "d4d49e02-49d3-4dda-9ddc-d3bb984ae68d",
                            Description = "Readaptado",
                            Value = "36"
                        },
                        new
                        {
                            Id = "6be0fe30-8be3-4434-856b-2768f955f968",
                            Description = "ATE",
                            Value = "37"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Session");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoggedUsers");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "caba3853-fd8c-41e5-bb0c-782a562c48b6",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "a1c6e605-a927-438b-9960-66f5f25e79b8",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "a01b604f-b160-42ff-ac23-87ca1b08a7f8",
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = "a3c4415b-33e9-4de0-9786-c28074fb8543",
                            Name = "Diretor"
                        },
                        new
                        {
                            Id = "a0f1e0c9-9200-48eb-a939-0be4c661ac25",
                            Name = "Secretario(a)"
                        },
                        new
                        {
                            Id = "370af61b-3167-40ff-ace5-203beeb21c61",
                            Name = "Auxiliar"
                        },
                        new
                        {
                            Id = "09006115-2282-42d9-99b3-6384083ab92c",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = "65c0cf20-6d47-43fa-84df-d83d408679e3",
                            Name = "Responsavel"
                        },
                        new
                        {
                            Id = "b3e6f9c3-d018-4a62-a014-f315536be3a7",
                            Name = "Aluno"
                        });
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessLevelId");

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StudentId");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.Code", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Organization.LogControl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("ModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("LogControls");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.StudentCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("StudentCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithMany("Codes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Academic.TeacherCode", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Organization.Code", "Code")
                        .WithMany("TeacherCodes")
                        .HasForeignKey("CodeId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithMany("Codes")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("LoginStatus")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Authentication.LoggedUser", "UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.AccessLevel", "AccessLevel")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SME.Pedagogico.Gestao.Models.Entity.Profile", b =>
                {
                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "StudentId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Academic.Teacher", "Teacher")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "TeacherId");

                    b.HasOne("SME.Pedagogico.Gestao.Models.Authentication.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SME.Pedagogico.Gestao.Models.Entity.Profile", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
