export const montarObjetoUsuario = ({
  permissoes,
  usuario,
  username,
  perfilSelecionado,
}) => ({
  name: "",
  username,
  email: "",
  token: usuario.token,
  session: "",
  refreshToken: "",
  isAuthenticated: usuario.autenticado,
  lastAuthentication: new Date(),
  roles: "",
  activeRole: null,
  listOccupations: "",
  permissoes,
  possuiPerfilSmeOuDre: usuario.perfisUsuario.possuiPerfilSmeOuDre,
  possuiPerfilDre: usuario.perfisUsuario.possuiPerfilDre,
  possuiPerfilSme: usuario.perfisUsuario.possuiPerfilSme,
  ehProfessorCj: usuario.perfisUsuario.ehProfessorCj,
  ehProfessor: usuario.perfisUsuario.ehProfessor,
  ehProfessorPoa: usuario.perfisUsuario.ehProfessorPoa,
  ehProfessorCjInfantil: usuario.perfisUsuario.ehProfessorCjInfantil,
  ehProfessorInfantil: usuario.perfisUsuario.ehProfessorInfantil,
  perfil: { perfis: usuario.perfisUsuario.perfis, perfilSelecionado },
});
