export const montarObjetoUsuario = ({
  permissoes,
  usuario,
  token,
  username,
  isAuthenticated,
  perfil,
}) => ({
  name: "",
  username,
  email: "",
  token,
  session: "",
  refreshToken: "",
  isAuthenticated,
  lastAuthentication: new Date(),
  roles: "",
  activeRole: null,
  listOccupations: "",
  permissoes,
  possuiPerfilSmeOuDre: usuario.possuiPerfilSmeOuDre,
  possuiPerfilDre: usuario.possuiPerfilDre,
  possuiPerfilSme: usuario.possuiPerfilSme,
  ehProfessorCj: usuario.ehProfessorCj,
  ehProfessor: usuario.ehProfessor,
  ehProfessorPoa: usuario.ehProfessorPoa,
  ehProfessorCjInfantil: usuario.ehProfessorCjInfantil,
  ehProfessorInfantil: usuario.ehProfessorInfantil,
  perfil,
});
