export const montarObjetoUsuario = ({
  permissoes,
  usuario,
  token,
  username,
  isAuthenticated,
  perfil,
}) => ({
  name: "",
  username,
  email: "",
  token,
  session: "",
  refreshToken: "",
  isAuthenticated,
  lastAuthentication: new Date(),
  roles: "",
  activeRole: null,
  listOccupations: "",
  permissoes,
  possuiPerfilSmeOuDre: usuario.possuiPerfilSmeOuDre || false,
  possuiPerfilDre: usuario.possuiPerfilDre || false,
  possuiPerfilSme: usuario.possuiPerfilSme || false,
  ehProfessorCj: usuario.ehProfessorCj || false,
  ehProfessor: usuario.ehProfessor || false,
  ehProfessorPoa: usuario.ehProfessorPoa || false,
  ehProfessorCjInfantil: usuario.ehProfessorCjInfantil || false,
  ehProfessorInfantil: usuario.ehProfessorInfantil || false,
  perfil,
});
